import type { ChecklistItem } from "@/lib/types/checklist";

export const dummyChecklist: ChecklistItem[] = [
  {
    id: "1",
    category: "burial",
    title: "사망신고",
    description: "사망일로부터 1개월 이내에 주민센터에 신고해야 합니다.",
    dueDays: 30,
    isUrgent: true,
    status: "done",
    guideUrl: null,
  },
  {
    id: "2",
    category: "finance",
    title: "금융거래 조회 (금융감독원 상속인 금융거래 조회)",
    description: "고인의 모든 금융 계좌, 보험, 채무를 한번에 조회합니다.",
    dueDays: 90,
    isUrgent: true,
    status: "in_progress",
    guideUrl: null,
  },
  {
    id: "3",
    category: "government",
    title: "건강보험 자격 상실 신고",
    description: "사망 후 14일 이내에 건강보험공단에 신고합니다.",
    dueDays: 14,
    isUrgent: true,
    status: "done",
    guideUrl: null,
  },
  {
    id: "4",
    category: "tax",
    title: "상속세 신고",
    description: "상속 개시일로부터 6개월 이내에 세무서에 신고해야 합니다.",
    dueDays: 180,
    isUrgent: true,
    status: "pending",
    guideUrl: null,
  },
  {
    id: "5",
    category: "legal",
    title: "상속 한정승인 또는 포기",
    description: "상속 개시를 안 날로부터 3개월 이내에 결정해야 합니다.",
    dueDays: 90,
    isUrgent: true,
    status: "pending",
    guideUrl: null,
  },
  {
    id: "6",
    category: "real_estate",
    title: "부동산 상속등기",
    description: "상속부동산의 소유권이전등기를 법원에 신청합니다.",
    dueDays: null,
    isUrgent: false,
    status: "pending",
    guideUrl: null,
  },
  {
    id: "7",
    category: "finance",
    title: "고인 명의 계좌 해지 및 상속",
    description: "각 은행 방문하여 상속 절차를 진행합니다.",
    dueDays: null,
    isUrgent: false,
    status: "pending",
    guideUrl: null,
  },
  {
    id: "8",
    category: "government",
    title: "연금 수급 정지 신고",
    description: "국민연금공단에 수급자 사망 신고 후 미지급 연금을 청구합니다.",
    dueDays: null,
    isUrgent: false,
    status: "pending",
    guideUrl: null,
  },
];
